import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import OverlayProviderWrapper from "./_components/providers/OverlayProviderWrapper";
import ConditionalLayout from "./_components/ConditionalLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased min-h-screen">
        <ThemeProvider>
          <OverlayProviderWrapper>
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
          </OverlayProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
