import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Toolbar from "./_components/toolbar/toolbar";
import { ThemeProvider } from "./_components/theme-provider";
import LeftContainer from "./_components/left-container/left-container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider >
          <LeftContainer />
          <Toolbar />
          <div
            className="flex flex-col absolute w-full h-full"
            style={{
              transform: "translate(200px, 60px)", // 위치 이동
              width: "calc(100% - 200px)", // LeftContainer 제외한 너비
              height: "calc(100% - 60px)", // Toolbar 제외한 높이
            }}
          >
            {children}
            {/* <FooterContainer /> */}
          </div>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
