import type { Metadata } from "next";
import "./globals.css";
import Toolbar from "./_components/toolbar/toolbar";
import { ThemeProvider } from "./_components/theme-provider";
import LeftContainer from "./_components/left-container/left-container";
import OverlayProviderWrapper from "./_components/providers/OverlayProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased flex flex-col h-screen overflow-x-auto overflow-y-auto`}
      >
        <ThemeProvider>
          <OverlayProviderWrapper>
            <Toolbar />
            <div className="flex flex-1 pt-[65px] overflow-auto">
              <LeftContainer />
              <div className="flex-1 overflow-x-auto overflow-y-auto">
                {children}
                {/* <FooterContainer /> */}
              </div>
            </div>
          </OverlayProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
